name: build

on:
  push:
  pull_request:
  release:
    types:
      - published

jobs:

  source:
    name: Build source package
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: docker://python
        with:
          args: 'sh -c "pip install build && python -m build --sdist"'

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*

  wheels:
    name: Build binary packages
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.10.2
        env:
          # Skip Python 3.11 builds; Scipy wheels are not yet built for Python 3.11
          # Skip PyPy builds; Astropy wheels are not built for PyPy.
          # Skip i686 builds.
          # Skip MUSL libc builds.
          CIBW_SKIP: 'cp311-* pp* *_i686 *-musllinux_*'

      - uses: actions/upload-artifact@v3
        with:
          path: wheelhouse/*

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [source, wheels]
    if: github.event_name == 'release'

    steps:
      - uses: actions/download-artifact@v3

      - uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: artifact/
